name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Package Lambda Function
      run: |
        mkdir -p package
        cp lambda_function.py package/
        pip install -r requirements.txt -t package/
        cd package
        zip -r ../lambda_function.zip .

    - name: Deploy to AWS Lambda
      uses: aws-actions/aws-lambda-deploy@v1
      with:
        aws-access-key-id: ${{ ASIAYLONDJ5VXXBTIYX3 }}
        aws-secret-access-key: ${{ 1oZE1gZF8nM1wm5y9kAs10mKykesupYo89MgK0R4 }}
        aws-region: 'us-east-1'
        function-name: 'lambda_function'
        zip-file: 'lambda_function.zip'

